services:
  jenkins:
    image: myjenkins-blueocean:2.479.3-1
    container_name: jenkins
    restart: on-failure
    privileged: true
    environment:
      - DOCKER_HOST=tcp://host.docker.internal:2375
    volumes:
      - jenkins-data:/var/jenkins_home
    ports:
      - "8080:8080"
      - "50000:50000"

volumes:
  jenkins-data:
